improve
Signed-off-by: Aviel Segev <asegev@redhat.com>

diff --git a/.github/workflows/target_repo_update.yml b/.github/workflows/target_repo_update.yml
--- a/.github/workflows/target_repo_update.yml
+++ b/.github/workflows/target_repo_update.yml
@@ -15,28 +15,37 @@ jobs:
       BRANCH_NAME: "auto-update-sha"
       MIGRATION_PLANNER_AGENT_UI_REPO_NAME: "AvielSegev/source"
       CONFIG_FILE: "build/config.txt"
+      TOKEN: ${{ secrets.GITHUB_TOKEN }} # Using the default token
 
     steps:
       - uses: actions/checkout@v4
 
       - name: Read payload
         id: payload
+        env:
+          SHA: ${{ github.event.client_payload.sha }}
+          REPO: ${{ github.event.client_payload.repo }}
         run: |
-          echo "new_sha=${{ github.event.client_payload.sha }}" >> $GITHUB_OUTPUT
-          echo "repo=${{ github.event.client_payload.repo }}" >> $GITHUB_OUTPUT
+          echo "new_sha=$SHA" >> $GITHUB_OUTPUT
+          echo "repo=$REPO" >> $GITHUB_OUTPUT
 
       - name: Update file
         id: update
+        env:
+          NEW_SHA: ${{ steps.payload.outputs.new_sha }}
         run: |
-          NEW_SHA=${{ steps.payload.outputs.new_sha }}
           sed -i "s/^my_sha_key=.*/my_sha_key=$NEW_SHA/" "$CONFIG_FILE"
+          grep -q "^my_sha_key=$NEW_SHA" "$CONFIG_FILE" || { echo "ERROR: sed substitution failed"; exit 1; }
 
       - name: Create Pull Request
         if: ${{ steps.payload.outputs.repo == env.MIGRATION_PLANNER_AGENT_UI_REPO_NAME }}
-        uses: peter-evans/create-pull-request@v5
+        uses: peter-evans/create-pull-request@v8
         with:
+          token: ${{ env.TOKEN }}
           branch: ${{ env.BRANCH_NAME }}
-          commit-message: "chore: Trigger konflux pipeline. The latest sha in repo ${{ env.MIGRATION_PLANNER_AGENT_UI_REPO_NAME }} was changed to ${{ steps.payload.outputs.new_sha }}."
+          commit-message: |
+            chore: Trigger konflux pipeline. 
+            Reason: The latest sha in repo ${{ env.MIGRATION_PLANNER_AGENT_UI_REPO_NAME }} was changed to ${{ steps.payload.outputs.new_sha }}.
           title: "Update agent-ui Repo HEAD"
           body: |
             Auto update triggered by ${{ steps.payload.outputs.repo }}.
